import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import NoiseBackground from "@/components/bg";
import FloatingNav from "@/components/nav";

const horrorFont = localFont({
  src: "../public/OPTIBrianJamesBoldCond.woff",
  display: "swap",
  variable: "--font-horror",
});

const pixelFont = localFont({
  src: "../public/DepartureMono-Regular.woff",
  display: "swap",
  variable: "--font-pixel",
});

export const metadata: Metadata = {
  title: "how ts wen rk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${horrorFont.variable} ${pixelFont.className} bg-[#050505] bg-linear-to-b from-[#010101] via-[#061930] to-[#054E96]`}
      >
        <FloatingNav />
        <div className="pointer-events-none fixed left-0 top-0 z-50 h-screen w-full">
          <div className="crt pointer-events-none fixed left-0 top-0 z-50 h-screen w-full" />
          <div className="lines" />
          <NoiseBackground />
        </div>
        <div className="relative h-screen w-full overflow-auto ">
          {children}
        </div>
      </body>
    </html>
  );
}
